In [1]:
import numpy as np

## Arrays creation tools

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.linspace(0, 10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(4)

array([0.59469093, 0.5162263 , 0.93776618, 0.85814736])

In [11]:
np.random.randint(1,15, (3,3))

array([[ 5, 13,  9],
       [12,  8, 14],
       [12, 14,  2]])

## Shape and reshape

In [13]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [14]:
arr

array([[8, 8],
       [8, 4],
       [5, 3]])

In [17]:
arr.reshape(2,3)

array([[8, 8, 8],
       [4, 5, 3]])

In [18]:
arr.reshape((2,3), order='C') #Organize data as C language

array([[8, 8, 8],
       [4, 5, 3]])

In [19]:
arr.reshape((2,3), order='F') #Organize data as Fortran language

array([[8, 5, 4],
       [8, 8, 3]])

In [20]:
arr.reshape((2,3), order='A') #Organize data in system better way 

array([[8, 8, 8],
       [4, 5, 3]])

## Main numpy functions

In [23]:
arr = (np.random.randint(1,20,10)).reshape(2,5)
arr

array([[ 1, 13,  2, 19, 18],
       [13,  4, 10, 17,  2]])

Selects the higher number in the array

In [25]:
arr.max()

19

0 for columns, 1 to n for the respective dimentions 

In [26]:
arr.max(1)

array([19, 17])

With _arg_ we look if the higher value is in the selected index

In [27]:
arr.argmax(0)

array([1, 0, 1, 0, 0])

With _ptp_ we can look the distance between the min value and the max value

In [28]:
arr.ptp(0)

array([12,  9,  8,  2, 16])

Concatenate

In [36]:
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])
print(a,b)

[[1 2]
 [3 4]] [5 6]


In [30]:
np.concatenate((a,b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [31]:
print(a.ndim,b.ndim)

2 1


In [32]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.concatenate((a,b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [34]:
b.T

array([[5],
       [6]])

In [35]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])